services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - database.env
    volumes:
      - shared-db-data:/var/lib/postgresql/data

  notification-db:
    image: postgres
    container_name: notification-postgres-db
    restart: always
    ports:
      - '5435:5432'
    env_file:
      - database.env
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    env_file:
      - database.env
    ports:
      - '3306:3306'
    volumes:
      - maria-db-data:/var/lib/mysql

  rabbitmq:
    image: mirror.gcr.io/rabbitmq:4.0.8 # TODO: This version should be updated to the latest one once its bug free.
    ports:
      - '5672:5672'

  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - database.env
    environment:
      - REDIS_PASSWORD
      - REDIS_PORT
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/root/redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"

  # Minio is used for storing files and images.
  # It is used for storing files and images.
  # It is used for storing files and images.
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  console:
    image: minio/console:latest
    ports:
      - '9090:9090'
    environment:
      CONSOLE_MINIO_SERVER: http://minio:9000
    depends_on:
      - minio

volumes:
  shared-db-data:
  redis_data:
  notification-db-data:
  maria-db-data:
  minio_data:
    driver: local
