export enum ComplaintPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum ComplaintIssueType {
  TUTOR_NOT_ATTENDED = 'TUTOR_NOT_ATTENDED',
  TUTOR_NOT_RESPONDING = 'TUTOR_NOT_RESPONDING',
  TUTOR_NOT_QUALIFIED = 'TUTOR_NOT_QUALIFIED',
  TUTOR_NOT_PROFESSIONAL = 'TUTOR_NOT_PROFESSIONAL',
  TUTOR_NOT_POLITE = 'TUTOR_NOT_POLITE',
  TUTOR_NOT_ENGAGING = 'TUTOR_NOT_ENGAGING',
}
