export enum ESessionStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  POSTPONED = 'POSTPONED',
  CANCELLED = 'CANCELLED',
  IN_PROGRESS = 'IN_PROGRESS',
  EXTENDED = 'EXTENDED',
  COMPLAINED = 'COMPLAINED',
}

export enum ESessionAcceptanceStatus {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export enum ESessionJoinStatus {
  STUDENT_JOINED = 'STUDENT_JOINED',
  STUDENT_LEFT = 'STUDENT_LEFT',
  TUTOR_JOINED = 'TUTOR_JOINED',
  TUTOR_LEFT = 'TUTOR_LEFT',
  NONE_JOINED = 'NONE_JOINED',
  BOTH_JOINED = 'BOTH_JOINED',
}
