export enum EComplaintStatus {
  ADMIN_PENDING = 'ADMIN_PENDING',
  RESOLVED = 'RESOLVED',
  FLAGGED = 'FLAGGED',
  ADMIN_IN_REVIEW = 'ADMIN_IN_REVIEW',
  ADMIN_REJECTED = 'ADMIN_REJECTED',
  TUTOR_PENDING = 'TUTOR_PENDING',
  TUTOR_IN_REVIEW = 'TUTOR_IN_REVIEW',
  TUTOR_REJECTED = 'TUTOR_REJECTED',
}
