export enum ENotificationMessageType {
  PASSWORD_RESET = 'PASSWORD_RESET',
  AUTONOMOUS_SERVICE_CREATION = 'AUTONOMOUS_SERVICE_CREATION',
  INVITATION_CREATION = 'INVITATION_CREATION',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_DELETED = 'INVITATION_DELETED',
  BID_SUBMITTED = 'BID_SUBMITTED',
  BID_ACCEPTED = 'BID_ACCEPTED',
  BID_REJECTED = 'BID_REJECTED',
  COUNTER_BID_SUBMITTED = 'COUNTER_BID_SUBMITTED',
}
