export enum ENotificationMessageType {
  PASSWORD_RESET = 'PASSWORD_RESET',
  AUTONOMOUS_SERVICE_CREATION = 'AUTONOMOUS_SERVICE_CREATION',
  INVITATION_CREATION = 'INVITATION_CREATION',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_DELETED = 'INVITATION_DELETED',
}
