export enum EUserRole {
  STUDENT = 'STUDENT',
  LECTURE = 'LECTURE',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  COLLEGE_ADMIN = 'COLLEGE_ADMIN',
  INCUBATION_CENTER_STAFF = 'INCUBATION_CENTER_STAFF',
  HoD = 'HEAD_OF_DEPARTMENT',
  INSTITUTIONAL_ADMIN = 'INSTITUTIONAL_ADMIN',
  QA = 'QUALITY_ASSURANCE_STAFF',
}
