name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_HOST << EOF
            # Exit on any error
            set -e

            # Error handling
            trap 'echo "Error on line \$LINENO"' ERR

            # Source profile and NVM
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"

            cd ${DEPLOY_PATH}

            git checkout main
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies
            yarn install --immutable

            # Build the applications
            yarn build core-service
            yarn build notification-service

            # Docker operations
            echo "$SERVER_PASSWORD" | sudo -S docker compose down
            echo "$SERVER_PASSWORD" | sudo -S docker compose build --no-cache
            echo "$SERVER_PASSWORD" | sudo -S docker compose up -d

            # Cleanup
            echo "$SERVER_PASSWORD" | sudo -S docker system prune -f
          EOF
